import { Plus_Jakarta_Sans } from "next/font/google";
import "./globals.css";
import NextTopLoader from 'nextjs-toploader';
import AccessibilityUserWay from "./helpers/AccessibilityUserWay";
import Header from "./layouts/Header";
import BackToTop from "./helpers/BackToTop";
import PopCash from "./helpers/popCash"; // Keeping this from HEAD
import GoogleAnalytics from "./helpers/googleAnaliytics";
import Footer from "./layouts/Footer";
import GoogleAds from "./helpers/GoogleAds";
import GoogleTagManager from "./helpers/GoogleTagManager";

const plusJakartaSans = Plus_Jakarta_Sans({ subsets: ["latin"] });

export const metadata = {
  title: "Jobim",
  description: "מציאת עבודה בקלות", // Keeping the incoming version
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <meta name="description" content="Generated by create next app" />
        <meta
          name="google-adsense-account"
          content="ca-pub-8986453606609093"
        ></meta>
        <meta name="ppck-ver" content="03fc6af4fab659d7336ff4b70b2d8052" />
        <link rel="icon" type="image/x-icon" href="/favicon.ico"></link>
        
        {/* Google Tag Manager script retained from HEAD */}
        <GoogleTagManager/>
      </head>
      <body
        className={`${plusJakartaSans.className} bg-light-yellow text-right`}
      >
        <NextTopLoader color="#FFF" height={3} />
        <Header />
        {children}

        <Footer/>
        
        {/* Keeping elements from both HEAD and version-four */}
        <AccessibilityUserWay />
        <BackToTop />
        {/* <PopCash /> */}
        <GoogleAnalytics/>
        <GoogleAds/>

        

        {/* Google Tag Manager (noscript) retained from HEAD */}
        <noscript>
          <iframe
            src="https://www.googletagmanager.com/ns.html?id=GTM-PW479H9W"
            height="0"
            width="0"
            style={{ display: "none", visibility: "hidden" }}
          ></iframe>
        </noscript>
      </body>
    </html>
  );
}
